import * as THREE from 'three';
import type { Topic as BCFTopic } from '../bcf/topic';
import { Nullable } from '../../types';
import { TopicCameraState } from '../../../example/types';

const defaultVector3 = new THREE.Vector3(-1, -1, -1).toArray();

export interface TopicParams extends BCFTopic {
    /**
     * Position of the camera in local three.js space.
     */
    position: THREE.Vector3Tuple;
    /**
     * Direction of the camera in local three.js space.
     */
    direction: THREE.Vector3Tuple;
    /**
     * target vector of the camera in local three.js space.
     */
    target: THREE.Vector3Tuple;
}

export interface TopicJSON extends TopicParams {
    readonly uuid: string;
    /**
     * Screenshot generated by three.js.
     */
    screenshot: string;
    /**
     *
     */
    order: number;
}

/**
 * Three.js wrapper for BCF topic.
 */
export class Topic implements TopicJSON {
    public uuid: string;

    public order: number;

    /**
     * Position of the camera in local three.js space.
     */
    position: THREE.Vector3Tuple;
    /**
     * Direction of the camera in local three.js space.
     */
    direction: THREE.Vector3Tuple;
    /**
     * target vector of the camera in local three.js space.
     */
    target: THREE.Vector3Tuple;

    /**
     * Screenshot generated by three.js.
     */
    screenshot: string;

    /**
     * Title of the topic.
     */
    title: string;
    /**
     * Description of the topic.
     */
    description: string;

    public constructor() {
        this.uuid = THREE.MathUtils.generateUUID();
        this.order = 0;

        this.direction = defaultVector3;
        this.position = defaultVector3;
        this.target = defaultVector3;
        this.screenshot = '';
        this.title = '';
        this.description = '';
    }

    /**
     * Set topic.
     */
    public set(params: Nullable<TopicParams>) {
        this.checkJSON(params);
        const { direction, position, target, title, description } = params as TopicParams;
        this.direction = direction;
        this.position = position;
        this.target = target;
        this.title = title;
        this.description = description;
    }

    /**
     * Get topic.
     * It will throw an error if topic is not set.
     */
    public get(): TopicParams {
        const topic: Nullable<TopicParams> = {
            direction: this.direction,
            position: this.position,
            target: this.target,
            title: this.title,
            description: this.description,
        };

        this.checkJSON(topic);

        return topic as TopicParams;
    }

    public setScreenshot(screenshot: string) {
        // TODO: Verify screenshot is a valid base64 string.
        this.screenshot = screenshot;
    }

    /**
     * Return topic as JSON string.
     */
    public toJSON(): TopicJSON {
        const json: Nullable<TopicJSON> = {
            uuid: this.uuid,
            direction: this.direction,
            position: this.position,
            target: this.target,
            screenshot: this.screenshot,
            title: this.title,
            description: this.description,
            order: this.order,
        };

        this.checkJSON(json);

        return json as TopicJSON;
    }

    /**
     * Create topic from JSON string.
     */
    public fromJSON(json: Nullable<TopicJSON>): void {
        if (json == null) throw new Error('json is null');

        const { uuid } = json;
        if (uuid == null) throw new Error('uuid is null');

        this.checkJSON(json);

        const { direction, position, target, title, description, order } = json as TopicJSON;

        this.uuid = uuid;
        this.position = position;
        this.direction = direction;
        this.target = target;
        this.title = title;
        this.description = description;
        this.order = order;
    }

    /**
     * Check if JSON is valid.
     */
    private checkJSON(json: Nullable<TopicParams>): void {
        const { title, description } = json;
        this.checkCamera(json);
        if (title == null) throw new Error('title is null');
        if (description == null) throw new Error('description is null');
    }

    private checkCamera(json: Nullable<TopicCameraState>): void {
        const { direction, position, target } = json;

        if (direction == null) throw new Error('direction is null');
        if (position == null) throw new Error('position is null');
        if (target == null) throw new Error('position is null');
    }
}
